- package-lock.json
- package.json
- src/App.js
- src/pages/test/index.js
- src/routers/PrivateRoutes.js
- src/utils/PrivateRoutes.js
Implemented a simple routing system that uses a Private routes utility to handle user roles and displays only the pages the user has permission to access. Because there's no pages yet, the router displays test pages.
TO DO:
- Implement jwt autentication in PrivateRoutes.js when Ready
- Add the real pages to the Router when Ready
- Add a permision denied page instead of returning to the login page
> #8 authentication login - Placeholder routing system

- src/components/modal/index.jsx
- Se añadio el componente rechazar pago y confirmar pago en el archivo index.jsx en la carpeta modal.
- Se corrigio el color de los botones.
> #Adicion de modales pago

- src/components/navbar/index.jsx
Dynamic navbar already implemented
-Added "Mis proyectos" to PM navbar
-Removed an empty file from the navbar component
> #29-dynamic-navbar

- src/utils/getApiData.js
Fixed a bug in the bug fix that made it so an incorrect password granted access
Added support so that autorization can detect when the user ticket has expired.
Also, the previous build instruccions from the first pull request were wrong so here are the corrected ones
Build instructions:
Make sure everything is installed on the front running npm i
Download the backend project
Make sure everything is installed running npm i in the backend
Configure the database with the config file in config/database.json
Run "npx sequelize-cli db:migrate" and "npx sequelize-cli db:seed:all" to migrate and seed the database
Build the backend with npm dev run
Build the frontend with npm start
> Final final final pull request I hope

- package-lock.json
- package.json
- src/App.js
- src/components/table/PmTableDropdown.jsx
- src/components/table/PmTableTravelAll.jsx
- src/components/table/TableTravelAllowance.jsx
- src/pages/HistorialViaticos/PmTable.js
- src/styles/PmTable.css
- src/styles/TableBadges.css
- src/styles/TableStyle.css
Se creó una tabla para el project manager, variando el estilo de la tabla de viáticos general
> #30 pm screen merge into #17 tabla viaticos

- src/styles/RequestModal.css
Modifique el estilo de las letras en el concepto de gasto y monto para que fueran negritas.
> Fix: Fix letter style

- src/apis/getApiData.js
> Apis complete

- package.json
- src/App.js
- src/apis/getApiData.js
- src/components/BadgeStatus.jsx
- src/components/table/PmTableTravelAll.jsx
- src/components/table/PmTableTravelAllActive.jsx
- src/components/table/TableDropdown.jsx
- src/pages/HistorialViaticos/PmTable.js
Añadido funcionalidad a las pantallas de solicitud y historial de viaticos para que muestren la información de la base de datos segun su estado.
> #52 pm historial

- src/components/BadgeStatus.jsx
- src/components/table/PmTableTravelAll.jsx
- src/components/table/PmTableTravelAllActive.jsx
Si esto rompe todo el git, culpo al marco xd
> Correcion, revertido BadgeStatus a como era antes

- src/apis/getApiData.js
- src/components/BadgeStatus.jsx
- src/components/table/TableTravelAllowance.jsx
- src/styles/TableBadges.css
> Fix: TableTravelAll

- src/pages/HistorialViaticos/PmTable.js
Added route path as a key to PM table component so that on route change the PM table re-renders and is not frozen until refresh.
> Added key to PM table

- src/App.js
- src/components/table/PmTableTravelAll.jsx
- src/pages/HistorialViaticos/PmTable.js
Made PM request table show only pending requests and fixed historial viaticos table so that it only displays closed requests.
> Fixed funcionality of PM tables

- src/components/navbar/index.jsx
Cambie los nombres de las rutas para que se marcara en rojo el nombre de la pagina en la que se encuentra el usuario.
> Fix navbar

- src/App.js
- src/apis/gastosApiTabla.js
- src/components/ButtonForm/index.jsx
- src/components/Gastos/gastosOptDropdown.jsx
- src/components/Gastos/subtotal.jsx
- src/components/Gastos/tableGastos.jsx
- src/components/modal/index.jsx
- src/components/table/TableDropdown.jsx
- src/components/table/TableTravelAllowance.jsx
Reverts ITC2025/TC2005B-front-end#64
> Revert "#43 rechazo pago user"

- src/components/navbar/index_1.jsx
- src/styles/navbar.css
Cambios en la navbar 
Ahora al hacer pantallas pequeñas el username y su imagen entra en el dropdown menu
> Navbar fixes in dropdown menu

- src/components/SolicitarViaticos/RequestModal.jsx
- src/pages/SolicitarViaticos/SolicitarViaticos.js
- src/utils/PostExpenses.js
Finished Solicitud Viatico with connections to DB and redistributed the RequestModal layout
> #47 status solicitud viaticos

- src/apis/gastosApiTabla.js
> #25 gastos pantalla

- src/apis/gastosApiTabla.js
- src/apis/getApiData.js
- src/components/ButtonForm/index.jsx
- src/components/Gastos/tableGastos.jsx
- src/components/modal/index.jsx
- src/pages/Login/login.js
- src/styles/TableStyle.css
Now expense report creation saves files on server. Also added being able to see ticket pictures in front end.
> Finished fixing expense report creation

- src/components/table/TableDropdown.jsx
> fix: modal de rechazo y ver pago y el status "pagado"

- src/apis/gastosApiTabla.js
- src/components/Gastos/tableGastos.jsx
- src/components/modal/index.jsx
Now users can see facturas and open them in a new tab.
> Added funcionality to expense reports table

- src/components/table/AdminTableTravelAll.jsx
- src/components/table/TableDropdown.jsx
- src/components/table/TableDropdownHistorial.jsx
Reverts ITC2025/TC2005B-front-end#82
> #48 admin connect table

- src/components/EditGastos/index.jsx
Ay mi madre el bicho, SIUUUUUUUUUU
> fix: bug image

- src/components/EditGastos/index.jsx
> Revert "fix: bug image"

- public/index.html
- src/App.css
- src/components/Gastos/tableGastos.jsx
- src/components/ProyectosVer/index.jsx
- src/components/SolicitarViaticos/AddInputButton.jsx
- src/components/TablaProyectos/ProyectosDropdown.jsx
- src/components/TablaProyectos/index.jsx
- src/components/navbar/index.jsx
- src/components/table/AdminTableTravelAll.jsx
- src/components/table/AdminTableTravelAllRequest.jsx
- src/components/table/PmTableTravelAll.jsx
- src/components/table/TableTravelAllowance.jsx
- src/pages/SolicitarViaticos/SolicitarViaticos.js
- src/styles/SolicitarViaticos.css
- src/utils/PostExpenses.js
Checked typos in most pages
Added headers to all pages with missing title
Styled _Acciones_ row from Tables
Implemented search bar in **Proyectos**
Added filter delete from active requests in admin
Deleted console logs that were commented
> fixed-typos-styling-and-filters

- src/components/Gastos/tableGastos.jsx
Now image and file links work and reflect changes in backend for storing files in firebase.
> Fixed data retrieval on expense report table 

- src/components/ProyectosVer/index.jsx
- src/components/TablaProyectos/ProyectosDropdown.jsx
- src/components/table/PmTableDropdown.jsx
- src/components/table/PmTableTravelAll.jsx
- src/components/table/TableTravelAllowance.jsx
filtered _Eliminado_ from tables
added dropdown to projects/solicitud/id table and filtered options for each status
typos
> fixed-dropdowns-and-filters-from-tables

- src/apis/getApiData.js
- src/components/Gastos/gastosOptDropdown.jsx
- src/components/Gastos/tableGastos.jsx
- src/pages/Gastos/EditarGasto.js
Se añadieron los filtros de status para el boton de edit en gastos del user
> 56 edit gastos

- src/components/Gastos/gastosOptDropdown.jsx
Lo mismo que la 56 pero en vez de boton editar, boton borrar
> Adicion de filtro para borrar gasto

- src/components/Gastos/colInfoProyecto.jsx
- src/components/Gastos/subtotal.jsx
- src/components/Gastos/tableGastos.jsx
- src/components/ProyectosVer/index.jsx
- src/components/table/AdminTableTravelAll.jsx
- src/components/table/AdminTableTravelAllRequest.jsx
- src/components/table/TableTravelAllowance.jsx
- src/utils/mxnFormat.js
Añadido una funcion para que convierta todos los montos de pesos mexicanos de las tablas al formato apropiado.
> Formateo mexicano

- src/components/modal/index.jsx
- src/components/table/PmTableTravelAll.jsx
Rendereo condicional en modal
En PmTableTravel se añadio el PM a la info
> Cambio en rendereo de botones
